### ISSUE TITLE
Unable to locate Package Zenity issue

### ISSUE THREAD

**Issue by DagonJ** [FilipinoAkoShaders/LinuxRunner#1]
~ $ termux-change-repo
~$bash installer.sh
installer.sh: line 10: zenity: command not found
Checking availability of current mirror:
[*] https://linux.domainesia.com/applications/termux/termux-main: ok
Hit:1 https://linux.domainesia.com/applications/termux/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Checking availability of current mirror:
[*] https://linux.domainesia.com/applications/termux/termux-main: ok
Hit:1 https://linux.domainesia.com/applications/termux/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking availability of current mirror:
[*] https://linux.domainesia.com/applications/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package zenity

**Comment by FilipinoAkoShaders** [comment]
Are you sure you downloaded termux from FDroid? 

The sources look sus

```
pkg update
pkg install zenity
```

**Comment by FilipinoAkoShaders** [comment]
![Screenshot_20230716-225311](https://github.com/FilipinoAkoShaders/LinuxRunner/assets/92209213/3c94db4a-9336-496c-bf4c-ef186a4ce2f3)
It should look like this. are you sure termux is updated and from fdroid?
